export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const GET_CUSTOMER_DETAILS = 'GET_CUSTOMER_DETAILS';
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS';
export const GET_CUSTOMER_SERVICE_INFO = 'GET_CUSTOMER_SERVICE_INFO';
export const GET_CUSTOMER_SERVICE_INFO_SUCCESS =
  'GET_CUSTOMER_SERVICE_INFO_SUCCESS';
export const REGISTER_CUSTOMER_REQUEST = 'REGISTER_CUSTOMER_REQUEST';
export const REGISTER_CUSTOMER_SUCCESS = 'REGISTER_CUSTOMER_SUCCESS';
export const BROKER_INFO_REQUEST = 'BROKER_INFO_REQUEST';
export const BROKER_INFO_REQUEST_SUCCESS = 'BROKER_INFO_REQUEST_SUCCESS';
export const STOP_EMAIL_REQUEST = 'STOP_EMAIL_REQUEST';
export const STOP_EMAIL_REQEUST_SUCCESS = 'STOP_EMAIL_REQEUST_SUCCESS';
export const ACCESS_CODE_COUNT_INCREMENT = 'ACCESS_CODE_COUNT_INCREMENT';
export const CLEAR_ACCESS_CODE_COUNT = 'CLEAR_ACCESS_CODE_COUNT';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS';


