
//Reducers
export const SAVE_DONORS_STAKE_HOLDERS = 'SAVE_DONORS_STAKE_HOLDERS';


//API's
export const GET_ALL_DONORS_REQUEST = 'GET_ALL_DONORS_REQUEST';
export const GET_ALL_DONORS_SUCCESS = 'GET_ALL_DONORS_SUCCESS';

export const SAVE_DONOR_KIND_REQUEST = 'SAVE_DONOR_KIND_REQUEST';
export const SAVE_DONOR_KIND_SUCCESS = 'SAVE_DONOR_KIND_SUCCESS';

export const SAVE_DONOR_REQUEST = 'SAVE_DONOR_REQUEST';
export const SAVE_DONOR_SUCCESS = 'SAVE_DONOR_SUCCESS';

export const UPDATE_DONOR_REQUEST = 'UPDATE_DONOR_REQUEST';
export const UPDATE_DONOR_SUCCESS = 'UPDATE_DONOR_SUCCESS';

export const UPDATE_DONOR_KIND_REQUEST = 'UPDATE_DONOR_KIND_REQUEST';
export const UPDATE_DONOR_KIND_SUCCESS = 'UPDATE_DONOR_KIND_SUCCESS';

export const GET_DONOR_BY_ID_REQUEST = 'GET_DONOR_BY_ID_REQUEST';
export const GET_DONOR_BY_ID_SUCCESS = 'GET_DONOR_BY_ID_SUCCESS';


export const DELETE_DONOR_KIND_REQUEST ='DELETE_DONOR_KIND_REQUEST';
export const DELETE_DONOR_KIND_SUCCESS ='DELETE_DONOR_KIND_SUCCESS';

export const DELETE_DONOR_REQUEST = 'DELETE_DONOR_REQUEST';
export const DELETE_DONOR_SUCCESS = 'DELETE_DONOR_SUCCESS';

//Proposal Family Unit Module

export const SAVE_PROPOSAL_FAMILY_UNIT_REQUEST = 'SAVE_PROPOSAL_FAMILY_UNIT_REQUEST';
export const SAVE_PROPOSAL_FAMILY_UNIT_SUCCESS = 'SAVE_PROPOSAL_FAMILY_UNIT_SUCCESS'; 

export const UPDATE_PROPOSAL_FAMILY_UNIT_REQUEST = 'UPDATE_PROPOSAL_FAMILY_UNIT_REQUEST';
export const UPDATE_PROPOSAL_FAMILY_UNIT_SUCCESS = 'UPDATE_PROPOSAL_FAMILY_UNIT_SUCCESS';

export const GET_PROPOSAL_REQUEST = 'GET_PROPOSAL_REQUEST';
export const GET_PROPOSAL_SUCCESS = 'GET_PROPOSAL_SUCCESSs';

export const DELETE_PROPOSAL_FAMILY_UNIT_REQUEST = 'DELETE_PROPOSAL_FAMILY_UNIT_REQUEST';
export const DELETE_PROPOSAL_FAMILY_UNIT_SUCCESS = 'DELETE_PROPOSAL_FAMILY_UNIT_SUCCESS';

//Proposal

export const SAVE_PROPOSALS_REQUEST = 'SAVE_PROPOSALS_REQUEST';
export const SAVE_PROPOSALS_SUCCESS = 'SAVE_PROPOSALS_SUCCESS';

export const UPDATE_PROPOSALS_REQUEST = 'UPDATE_PROPOSALS_REQUEST';
export const UPDATE_PROPOSALS_SUCCESS = 'UPDATE_PROPOSALS_SUCCESS';

export const GET_PROPOSALS_REQUEST = 'GET_PROPOSALS_REQUEST';
export const GET_PROPOSALS_SUCCESS = 'GET_PROPOSALS_SUCCESSs';

export const DELETE_PROPOSALS_REQUEST = 'DELETE_PROPOSALS_REQUEST';
export const DELETE_PROPOSALS_SUCCESS = 'DELETE_PROPOSALS_SUCCESS';

export const GET_PROPOSALS_BY_PROPOSALID_REQUEST = 'GET_PROPOSALS_BY_PROPOSALID_REQUEST';
export const GET_PROPOSALS_BY_PROPOSALID_SUCCESS = 'GET_PROPOSALS_BY_PROPOSALID_SUCCESS';

//Master Data Info

export const GET_ALL_MASTER_DATA_INFO_REQUEST = 'GET_ALL_MASTER_DATA_INFO_REQUEST';
export const GET_ALL_MASTER_DATA_INFO_SUCCESS = 'GET_ALL_MASTER_DATA_INFO_SUCCESS';

//StakeHolders 

export const SAVE_STAKE_HOLDER_REQUEST = 'SAVE_STAKE_HOLDER_REQUEST';
export const SAVE_STAKE_HOLDER_SUCCESS = 'SAVE_STAKE_HOLDER_SUCCESS';

export const UPDATE_STAKE_HOLDER_REQUEST = 'UPDATE_STAKE_HOLDER_REQUEST';
export const UPDATE_STAKE_HOLDER_SUCCESS = 'UPDATE_STAKE_HOLDER_SUCCESS';

export const DELETE_STAKE_HOLDER_SUCCESS = 'DELETE_STAKE_HOLDER_SUCCESS';
export const DELETE_STAKE_HOLDER_REQUEST = 'DELETE_STAKE_HOLDER_REQUEST';



